#!/usr/bin/env bash
# Script to clean up file names...

for file in *; do
  case "$file" in
    *.jpeg) mv "$file" "${file%.*}.jpg"
           ;;
    *.JPG|*.AVI) mv "$file" "${file,,}"
           ;;
    *.mp4|*.avi|*.mkv) mv -n "$file" $(echo "$file" \
      | sed "s/\(S[0-9]\{2\}E[0-9]\{2\}\).*\.$ext/\1.$ext/")
           ;;
  esac
done

(( $? == 0 )) && printf "%s\n" "Cleanup completed..."

