#!/bin/bash

# provides DMENU_OPTIONS
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dmenu"
[[ -f "$CONFIG_DIR/dm_options" ]] && . "$CONFIG_DIR/dm_options"

DMENU="dmenu $DMENU_OPTIONS"
SELECTION=$(man -k . | $DMENU -l 10 | awk '{print $1}')

if [[ -n "$SELECTION" ]]; then
        man -Tpdf "$SELECTION" | zathura -
fi
